/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ano-ui/src/components/AAvatar/AAvatar.vue')['default']
    AAvatarGroup: typeof import('ano-ui/src/components/AAvatarGroup/AAvatarGroup.vue')['default']
    AButton: typeof import('ano-ui/src/components/AButton/AButton.vue')['default']
    ACell: typeof import('ano-ui/src/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('ano-ui/src/components/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('ano-ui/src/components/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('ano-ui/src/components/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ANavBar: typeof import('ano-ui/src/components/ANavBar/ANavBar.vue')['default']
    APage: typeof import('ano-ui/src/components/APage/APage.vue')['default']
    ARadio: typeof import('ano-ui/src/components/ARadio/ARadio.vue')['default']
    ARadioGroup: typeof import('ano-ui/src/components/ARadioGroup/ARadioGroup.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
    UGitHubButton: typeof import('./components/UGitHubButton.vue')['default']
    UThemeSwitcher: typeof import('./components/UThemeSwitcher.vue')['default']
  }
}
