/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AActionSheet: typeof import('ano-ui/src/components/AActionSheet/AActionSheet.vue')['default']
    AAvatar: typeof import('ano-ui/src/components/AAvatar/AAvatar.vue')['default']
    AAvatarGroup: typeof import('ano-ui/src/components/AAvatarGroup/AAvatarGroup.vue')['default']
    ABadge: typeof import('ano-ui/src/components/ABadge/ABadge.vue')['default']
    AButton: typeof import('ano-ui/src/components/AButton/AButton.vue')['default']
    ACell: typeof import('ano-ui/src/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('ano-ui/src/components/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('ano-ui/src/components/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('ano-ui/src/components/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ACollapse: typeof import('ano-ui/src/components/ACollapse/ACollapse.vue')['default']
    ACollapseItem: typeof import('ano-ui/src/components/ACollapseItem/ACollapseItem.vue')['default']
    ADialog: typeof import('ano-ui/src/components/ADialog/ADialog.vue')['default']
    AField: typeof import('ano-ui/src/components/AField/AField.vue')['default']
    ANavBar: typeof import('ano-ui/src/components/ANavBar/ANavBar.vue')['default']
    ANoticeBar: typeof import('ano-ui/src/components/ANoticeBar/ANoticeBar.vue')['default']
    ANotify: typeof import('ano-ui/src/components/ANotify/ANotify.vue')['default']
    AOverlay: typeof import('ano-ui/src/components/AOverlay/AOverlay.vue')['default']
    APage: typeof import('ano-ui/src/components/APage/APage.vue')['default']
    APopup: typeof import('ano-ui/src/components/APopup/APopup.vue')['default']
    ARadio: typeof import('ano-ui/src/components/ARadio/ARadio.vue')['default']
    ARadioGroup: typeof import('ano-ui/src/components/ARadioGroup/ARadioGroup.vue')['default']
    ASwitch: typeof import('ano-ui/src/components/ASwitch/ASwitch.vue')['default']
    ATabBar: typeof import('ano-ui/src/components/ATabBar/ATabBar.vue')['default']
    ATabBarItem: typeof import('ano-ui/src/components/ATabBarItem/ATabBarItem.vue')['default']
    ATag: typeof import('ano-ui/src/components/ATag/ATag.vue')['default']
    AToast: typeof import('ano-ui/src/components/AToast/AToast.vue')['default']
    ATransition: typeof import('ano-ui/src/components/ATransition/ATransition.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
    UGitHubButton: typeof import('./components/UGitHubButton.vue')['default']
    UThemeSwitcher: typeof import('./components/UThemeSwitcher.vue')['default']
  }
}
