export const radioShortcuts: Record<string, string> = {
  'a-radio-base': 'flex items-center',
  'a-radio-mini': 'text-xs',
  'a-radio-small': 'text-sm',
  'a-radio-normal': 'text-base',
  'a-radio-large': 'text-lg',
  'a-radio-disabled': 'bg-[#EBEDF0] border-[#C8C9CC] dark:bg-[#3A3A3C] text-[#C8C9CC] dark:text-[#4D4D4D]',
  'a-radio-disabled-label': 'text-[#C8C9CC] dark:text-[#4D4D4D]',
  'a-radio-radio-base': 'relative border border-solid border-[#C8C9CC] rounded-full transition-all duration-200',
  'a-radio-radio-mini': 'h5 w5',
  'a-radio-radio-small': 'h6 w6',
  'a-radio-radio-normal': 'h7 w7',
  'a-radio-radio-large': 'h8 w8',
  'a-radio-radio-dot': 'absolute inset-0 flex justify-center items-center',
  'a-radio-radio-dot-mini': 'h2 w2',
  'a-radio-radio-dot-small': 'h3 w3',
  'a-radio-radio-dot-normal': 'h4 w4',
  'a-radio-radio-dot-large': 'h5 w5',
}
