/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "pages/index" |
       "pages/action/action-sheet" |
       "pages/action/dialog" |
       "pages/action/notify" |
       "pages/action/overlay" |
       "pages/basic/avatar" |
       "pages/basic/button" |
       "pages/basic/cell" |
       "pages/basic/popup" |
       "pages/basic/toast" |
       "pages/basic/transition" |
       "pages/display/badge" |
       "pages/display/collapse" |
       "pages/display/notice-bar" |
       "pages/display/tag" |
       "pages/form/checkbox" |
       "pages/form/field" |
       "pages/form/radio" |
       "pages/form/switch" |
       "pages/navigation/nav-bar" |
       "pages/navigation/tab-bar";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
