/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AActionSheet: typeof import('./../../packages/components/AActionSheet/AActionSheet.vue')['default']
    AButton: typeof import('./../../packages/components/AButton/AButton.vue')['default']
    ACell: typeof import('./../../packages/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('./../../packages/components/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('./../../packages/components/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('./../../packages/components/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ADialog: typeof import('./../../packages/components/ADialog/ADialog.vue')['default']
    AField: typeof import('./../../packages/components/AField/AField.vue')['default']
    ANoticeBar: typeof import('./../../packages/components/ANoticeBar/ANoticeBar.vue')['default']
    ANotify: typeof import('./../../packages/components/ANotify/ANotify.vue')['default']
    AOverlay: typeof import('./../../packages/components/AOverlay/AOverlay.vue')['default']
    APage: typeof import('./../../packages/components/APage/APage.vue')['default']
    APopup: typeof import('./../../packages/components/APopup/APopup.vue')['default']
    ARadio: typeof import('./../../packages/components/ARadio/ARadio.vue')['default']
    ARadioGroup: typeof import('./../../packages/components/ARadioGroup/ARadioGroup.vue')['default']
    ASwitch: typeof import('./../../packages/components/ASwitch/ASwitch.vue')['default']
    ATag: typeof import('./../../packages/components/ATag/ATag.vue')['default']
    AToast: typeof import('./../../packages/components/AToast/AToast.vue')['default']
    ATransition: typeof import('./../../packages/components/ATransition/ATransition.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
  }
}
