/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AActionSheet: typeof import('./ano-ui/AActionSheet/AActionSheet.vue')['default']
    AButton: typeof import('./ano-ui/AButton/AButton.vue')['default']
    ACell: typeof import('./ano-ui/ACell/ACell.vue')['default']
    ACellGroup: typeof import('./ano-ui/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('./ano-ui/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('./ano-ui/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ADialog: typeof import('./ano-ui/ADialog/ADialog.vue')['default']
    AField: typeof import('./ano-ui/AField/AField.vue')['default']
    ANoticeBar: typeof import('./ano-ui/ANoticeBar/ANoticeBar.vue')['default']
    ANotify: typeof import('./ano-ui/ANotify/ANotify.vue')['default']
    AOverlay: typeof import('./ano-ui/AOverlay/AOverlay.vue')['default']
    APage: typeof import('./ano-ui/APage/APage.vue')['default']
    APopup: typeof import('./ano-ui/APopup/APopup.vue')['default']
    ARadio: typeof import('./ano-ui/ARadio/ARadio.vue')['default']
    ARadioGroup: typeof import('./ano-ui/ARadioGroup/ARadioGroup.vue')['default']
    ASwitch: typeof import('./ano-ui/ASwitch/ASwitch.vue')['default']
    ATag: typeof import('./ano-ui/ATag/ATag.vue')['default']
    AToast: typeof import('./ano-ui/AToast/AToast.vue')['default']
    ATransition: typeof import('./ano-ui/ATransition/ATransition.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
  }
}
