export const switchShortcuts: Record<string, string> = {
  'a-switch-base': 'inline-flex border border-solid rounded-full a-transition dark:border-op80 relative a-softBg',
  'a-switch-xs': 'min-w7 h4 text-xs',
  'a-switch-sm': 'min-w9 h5 text-sm',
  'a-switch-md': 'min-w11 h6 text-base',
  'a-switch-lg': 'min-w13 h7 text-lg',
  'a-switch-xl': 'min-w15 h8 text-xl',
  'a-switch-dot': 'absolute left-0.5 right-auto top-0.5 bottom-0.5 rounded-full bg-white a-transition flex items-center justify-center',
  'a-switch-dot-checked': 'left-50%',
  'a-switch-dot-xs': 'min-w3 h3',
  'a-switch-dot-sm': 'min-w4 h4',
  'a-switch-dot-md': 'min-w5 h5',
  'a-switch-dot-lg': 'min-w6 h6',
  'a-switch-dot-xl': 'min-w7 h7',
  'a-switch-active-label': 'absolute left-0.5 right-auto top-0.5 bottom-0.5 a-transition flex items-center justify-center animate-zoom-in animate-duration-200 !leading-none',
  'a-switch-inactive-label': 'a-switch-active-label left-50%',
}
