export const switchShortcuts: Record<string, string> = {
  'a-switch-base': 'border border-solid bg-clip-padding rounded-full a-transition dark:border-op80 relative a-softBg',
  'a-switch-mini': 'min-w9 h5 text-xs',
  'a-switch-small': 'min-w11 h6 text-sm',
  'a-switch-normal': 'min-w13 h7 text-base',
  'a-switch-large': 'min-w15 h8 text-lg',
  'a-switch-disabled': 'bg-[#EBEDF0] border-[#EBEDF0] dark:bg-[#3A3A3C] dark:border-[#3A3A3C] text-[#C8C9CC] dark:text-[#4D4D4D]',
  'a-switch-dot': 'absolute left-0.5 right-auto top-0.5 bottom-0.5 rounded-full bg-white a-transition flex items-center justify-center',
  'a-switch-dot-disabled': 'bg-[#C8C9CC] dark:bg-[#4D4D4D] text-[#C8C9CC] dark:text-[#4D4D4D]',
  'a-switch-dot-checked': 'left-50%',
  'a-switch-dot-mini': 'min-w4 h4',
  'a-switch-dot-small': 'min-w5 h5',
  'a-switch-dot-normal': 'min-w6 h6',
  'a-switch-dot-large': 'min-w7 h7',
  'a-switch-active-label': 'absolute left-0.5 right-auto top-0.5 bottom-0.5 a-transition flex items-center justify-center animate-zoom-in animate-duration-200 !leading-none',
  'a-switch-inactive-label': 'a-switch-active-label left-50%',
}
