/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AACollapse: typeof import('./ano-ui/components/AACollapse/AACollapse.vue')['default']
    AACollapseItem: typeof import('./ano-ui/components/AACollapseItem/AACollapseItem.vue')['default']
    AActionSheet: typeof import('./ano-ui/components/AActionSheet/AActionSheet.vue')['default']
    AAvatar: typeof import('./ano-ui/components/AAvatar/AAvatar.vue')['default']
    AAvatarGroup: typeof import('./ano-ui/components/AAvatarGroup/AAvatarGroup.vue')['default']
    ABadge: typeof import('./ano-ui/components/ABadge/ABadge.vue')['default']
    AButton: typeof import('./ano-ui/components/AButton/AButton.vue')['default']
    ACell: typeof import('./ano-ui/components/ACell/ACell.vue')['default']
    ACellGroup: typeof import('./ano-ui/components/ACellGroup/ACellGroup.vue')['default']
    ACheckbox: typeof import('./ano-ui/components/ACheckbox/ACheckbox.vue')['default']
    ACheckboxGroup: typeof import('./ano-ui/components/ACheckboxGroup/ACheckboxGroup.vue')['default']
    ACollapseTransition: typeof import('./ano-ui/components/ACollapseTransition/ACollapseTransition.vue')['default']
    ADialog: typeof import('./ano-ui/components/ADialog/ADialog.vue')['default']
    AField: typeof import('./ano-ui/components/AField/AField.vue')['default']
    ANavBar: typeof import('./ano-ui/components/ANavBar/ANavBar.vue')['default']
    ANoticeBar: typeof import('./ano-ui/components/ANoticeBar/ANoticeBar.vue')['default']
    ANotify: typeof import('./ano-ui/components/ANotify/ANotify.vue')['default']
    AOverlay: typeof import('./ano-ui/components/AOverlay/AOverlay.vue')['default']
    APage: typeof import('./ano-ui/components/APage/APage.vue')['default']
    APopup: typeof import('./ano-ui/components/APopup/APopup.vue')['default']
    ARadio: typeof import('./ano-ui/components/ARadio/ARadio.vue')['default']
    ARadioGroup: typeof import('./ano-ui/components/ARadioGroup/ARadioGroup.vue')['default']
    ASwitch: typeof import('./ano-ui/components/ASwitch/ASwitch.vue')['default']
    ATabBar: typeof import('./ano-ui/components/ATabBar/ATabBar.vue')['default']
    ATabBarItem: typeof import('./ano-ui/components/ATabBarItem/ATabBarItem.vue')['default']
    ATag: typeof import('./ano-ui/components/ATag/ATag.vue')['default']
    AToast: typeof import('./ano-ui/components/AToast/AToast.vue')['default']
    ATransition: typeof import('./ano-ui/components/ATransition/ATransition.vue')['default']
    UBasePage: typeof import('./components/UBasePage.vue')['default']
  }
}
